# Ant
# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
  
pool:
  name: Default

steps:
- script: |
   cd $CODE_DIR
   export CODE_DIR=${PWD}
   cd $CODE_DIR
   docker run -e CODE_DIR -v ${PWD}:${PWD}  scanmycode/scanmycode3-ce:worker-cli /bin/sh -c 'cd $CODE_DIR && checkmate init'
   docker run -e CODE_DIR -v ${PWD}:${PWD}  scanmycode/scanmycode3-ce:worker-cli /bin/sh -c 'cd $CODE_DIR && checkmate git init'
   docker run -e CODE_DIR -v ${PWD}:${PWD}  scanmycode/scanmycode3-ce:worker-cli /bin/sh -c 'cd $CODE_DIR && checkmate git analyze --branch `git rev-parse --abbrev-ref HEAD~1`' 
   docker run -e CODE_DIR -v ${PWD}:${PWD}  scanmycode/scanmycode3-ce:worker-cli /bin/sh -c 'cd $CODE_DIR && checkmate issues html'
  displayName: 'Betterscan - SAST'

