# Ant
# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
  
pool:
  name: Default
 
steps:
- script: |
    echo $PATH
    pwd
    wget https://raw.githubusercontent.com/marcinguy/betterscan-ce/master/cli.sh
    sh cli.sh
     displayName: 'Betterscan - SAST'

