# Ant
# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  System.Debug: True 
  
pool:
  name: Default
 
steps:
- script: |
    echo $PATH
    java -version
    which ant
    ant -version
  displayName: 'Run a multi-line script'
- task: Ant@1
  inputs:
    buildFile: 'build/build-sb.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
