# Ant
# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
  
pool:
  name: Default
 
steps:
- script: |
    echo $PATH
    java -version
    which ant
    ant -version
  displayName: 'Run a multi-line script'
- task: dependency-check-build-task@6
  inputs:
    projectName: 'Deloitte-DevSecOps.bodgeit'
    scanPath: $(Build.SourcesDirectory)/**/proj.*/*.csproj
    format: 'CSV'
